[build]
  base = "client/"
  publish = "client/build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
